services:
  e2e-rest-service:
    image: iomega/end-to-end-rest-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    env_file:
      - .env
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
