"""Utility Functions and Helpers"""

from .logger import (
    setup_logger,
    get_logger,
    add_context_to_logger,
    configure_default_logger,
    LogColors,
)

from .exceptions import (
    MSEv15E2EException,
    APIException,
    ValidationError,
    RateLimitError,
    AuthenticationError,
    AuthorizationError,
    ResourceNotFoundError,
    AgentException,
    AgentInitializationError,
    AgentExecutionError,
    AgentTimeoutError,
    ToolException,
    ToolExecutionError,
    MCPConnectionError,
    MCPServerUnavailableError,
    OrderManagementError,
    EmailSendError,
    SessionException,
    SessionNotFoundError,
    SessionExpiredError,
    SessionStorageError,
    ConfigurationError,
    DependencyError,
    format_exception_details,
    get_http_status_code,
    should_retry,
)

from .helpers import (
    generate_request_id,
    generate_session_id,
    get_utc_now,
    format_timestamp,
    parse_timestamp,
    mask_sensitive_value,
    compute_hash,
    sanitize_session_id,
    sanitize_tenant_id,
    truncate_string,
    safe_get,
    format_file_size,
    merge_dicts,
    parse_bool,
    chunk_list,
    remove_none_values,
)

__all__ = [
    # Logger
    "setup_logger",
    "get_logger",
    "add_context_to_logger",
    "configure_default_logger",
    "LogColors",
    # Exceptions
    "MSEv15E2EException",
    "APIException",
    "ValidationError",
    "RateLimitError",
    "AuthenticationError",
    "AuthorizationError",
    "ResourceNotFoundError",
    "AgentException",
    "AgentInitializationError",
    "AgentExecutionError",
    "AgentTimeoutError",
    "ToolException",
    "ToolExecutionError",
    "MCPConnectionError",
    "MCPServerUnavailableError",
    "OrderManagementError",
    "EmailSendError",
    "SessionException",
    "SessionNotFoundError",
    "SessionExpiredError",
    "SessionStorageError",
    "ConfigurationError",
    "DependencyError",
    "format_exception_details",
    "get_http_status_code",
    "should_retry",
    # Helpers
    "generate_request_id",
    "generate_session_id",
    "get_utc_now",
    "format_timestamp",
    "parse_timestamp",
    "mask_sensitive_value",
    "compute_hash",
    "sanitize_session_id",
    "sanitize_tenant_id",
    "truncate_string",
    "safe_get",
    "format_file_size",
    "merge_dicts",
    "parse_bool",
    "chunk_list",
    "remove_none_values",
]
